apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: potato
spec:
  project: default
  source:
    repoURL: git@github.com:0rg4n1z4t10n/docker-desktop-STATE-potato.git
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: potato
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
